# See the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    cooldown:
      default-days: 7
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
  - package-ecosystem: 'github-actions'
    cooldown:
      default-days: 7
    # Workflow files stored in the default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'daily'
