name: Regression

on: workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: |
            npm i -g pm2
            pm2 start ecosystem.config.json
